import { Property, ServiceType, UnitStatus, TimelineEventType, MaintenanceStatus, NominalCode, Stakeholder, StakeholderType, ContractorTrade, CommissioningInfo, IvolveStaff, ContactTier, PpmSchedule, Document, Person, PersonStatus, KeyDates, LegalEntity, ComplianceType, GrowthOpportunity, OpportunityType, BDStage, DevelopmentStage, BenefitType, ApplicationStage } from '../types';

const MOCK_COMMISSIONERS = {
    harrogate: { id: 'c-hg', name: 'Susan Collins', role: 'Commissioner', phone: '01423 500 600', email: 's.collins@northyorks.gov.uk' },
    nottingham: { id: 'c-ng', name: 'David Jones', role: 'Framework Lead', phone: '0115 915 5555', email: 'd.jones@nottinghamcity.gov.uk' },
    newport: { id: 'c-np', name: 'Rhian Evans', role: 'Commissioning Officer', phone: '01633 656 656', email: 'r.evans@newport.gov.uk' }
};

export const MOCK_PPM_SCHEDULES: PpmSchedule[] = [
    {
        id: 'ppm-1',
        name: 'Annual Gas Safety Inspection',
        complianceType: ComplianceType.GasSafety,
        frequencyMonths: 12,
        leadTimeDays: 30,
        scope: { type: 'All' }
    },
    {
        id: 'ppm-2',
        name: '5-Year Electrical Check (EICR) - North',
        complianceType: ComplianceType.EICR,
        frequencyMonths: 60,
        leadTimeDays: 60,
        scope: { type: 'Region', value: 'North' }
    },
];

const MOCK_DOCS_STRE00: Document[] = [
    { id: 'doc-1', name: 'Gas Safety Certificate 2024', type: 'PDF', date: '2024-05-15', year: 2024, url: '#', linkedJobRef: 'HAR-580' },
    { id: 'doc-2', name: 'EICR Report 2022', type: 'PDF', date: '2022-08-01', year: 2022, url: '#' },
    { id: 'doc-3', name: 'Lease Agreement', type: 'PDF', date: '2021-09-01', year: 2021, url: '#' },
];

const MOCK_KEY_DATES_STRE00: KeyDates = {
    lease: {
        startDate: '2021-09-01',
        term: '25 Years',
        endDate: '2046-08-31',
        breakDate: '2031-08-31',
    },
    sla: {
        startDate: '2021-09-01',
        term: '10 Years',
        renewalDate: '2030-09-01'
    }
};

const MOCK_PROPERTIES_EXPANDED: Property[] = [
    // New Properties
    {
        id: 'APPLE00_PROP',
        address: { propertyName: 'Apple House', line1: '5 Apple Street', city: 'Leeds', county: 'West Yorkshire', postcode: 'LS1 1AA', country: 'England' },
        tags: { rp: 'Inclusion Housing', supportProvider: 'ivolve', la: 'Leeds City Council' },
        region: 'North', serviceType: ServiceType.SupportedLiving, legalEntity: LegalEntity.Heathcotes, propertyType: 'Semi-detached', livingType: 'Shared Living',
        handoverDate: '2018-05-20', handbackDate: null, flags: [],
        units: [
            { id: 'APPLE00', name: 'Master', status: UnitStatus.Master }, { id: 'APPLE01', name: 'Room 1', status: UnitStatus.Occupied },
            { id: 'APPLE02', name: 'Room 2', status: UnitStatus.Occupied }, { id: 'APPLE03', name: 'Room 3', status: UnitStatus.Void },
            { id: 'APPLE04', name: 'Room 4', status: UnitStatus.Occupied }, { id: 'APPLE05', name: 'Staff Office', status: UnitStatus.StaffSpace },
        ],
        contacts: [], timeline: [], rentData: { currentSchedule: { year: '2024/25', documentUrl: '#', lines: [] }, previousSchedules: [], voidTerms: { initial: 'N/A', subsequent: 'N/A' } },
        maintenanceJobs: [
            { id: 'job-6', ref: 'LDS-101', propertyAddress: '5 Apple Street, Leeds', unit: 'Room 3', category: 'Plastering', nominalCode: NominalCode.DEC, priority: 'Medium', status: MaintenanceStatus.Open, reportedDate: '2024-07-25', slaDueDate: '2024-08-22', assignedTo: '', details: { reportedBy: 'Area Manager', method: 'Email', roomLocation: 'Bedroom', summary: 'Plastering required on one wall before new tenant moves in.', isTenantDamage: false, cost: {net:0,vat:0,gross:0} }, activityLog: [], jobType: 'Reactive' },
        ],
        complianceItems: [ { id: 'comp-apple-1', type: ComplianceType.GasSafety, lastCheck: '2024-06-01', nextCheck: '2025-05-31', status: 'Compliant', reportUrl: '#' } ],
        legalAgreements: [], documents: [], features: [], photos: ['https://picsum.photos/seed/APPLE01/800/600'], floorplans: []
    },
    {
        id: 'BANAN00_PROP',
        address: { propertyName: 'Banana Apartments', line1: '10 Banana Avenue', city: 'Birmingham', county: 'West Midlands', postcode: 'B1 1BB', country: 'England' },
        tags: { rp: 'Harbour Light', supportProvider: 'ivolve', la: 'Birmingham City Council' },
        region: 'Midlands', serviceType: ServiceType.Residential, legalEntity: LegalEntity.Gresham, propertyType: 'Flat in property', livingType: 'Self-contained',
        handoverDate: '2020-02-10', handbackDate: null, flags: [],
        units: [
            { id: 'BANAN00', name: 'Master', status: UnitStatus.Master }, { id: 'BANAN01', name: 'Flat 1', status: UnitStatus.Occupied },
            { id: 'BANAN02', name: 'Flat 2', status: UnitStatus.Occupied }, { id: 'BANAN03', name: 'Flat 3', status: UnitStatus.Occupied, attention: true },
        ],
        contacts: [], timeline: [], rentData: { currentSchedule: { year: '2024/25', documentUrl: '#', lines: [] }, previousSchedules: [], voidTerms: { initial: 'N/A', subsequent: 'N/A' } },
        maintenanceJobs: [],
        complianceItems: [ { id: 'comp-banana-1', type: ComplianceType.EICR, lastCheck: '2021-03-15', nextCheck: '2026-03-14', status: 'Compliant', reportUrl: '#' } ],
        legalAgreements: [], documents: [], features: [], photos: ['https://picsum.photos/seed/BANAN01/800/600'], floorplans: []
    },
     {
        id: 'CHERR00_PROP',
        address: { propertyName: 'Cherry Mews', line1: '15 Cherry Close', city: 'Manchester', county: 'Greater Manchester', postcode: 'M1 1CC', country: 'England' },
        tags: { rp: 'Auckland Home Solutions', supportProvider: 'ivolve', la: 'Manchester City Council' },
        region: 'North', serviceType: ServiceType.SupportedLiving, legalEntity: LegalEntity.TLC, propertyType: 'Detached', livingType: 'Mixed',
        handoverDate: '2021-11-01', handbackDate: null, flags: [{ id: 'flag-cherry-1', message: 'Parking restrictions apply Mon-Fri 9am-5pm.', level: 'info' }],
        units: [
            { id: 'CHERR00', name: 'Master', status: UnitStatus.Master }, { id: 'CHERR01', name: 'Flat A', status: UnitStatus.Occupied },
            { id: 'CHERR02', name: 'Room B', status: UnitStatus.Occupied }, { id: 'CHERR03', name: 'Room C', status: UnitStatus.Void },
        ],
        contacts: [], timeline: [], rentData: { currentSchedule: { year: '2024/25', documentUrl: '#', lines: [] }, previousSchedules: [], voidTerms: { initial: 'N/A', subsequent: 'N/A' } },
        maintenanceJobs: [], complianceItems: [], legalAgreements: [], documents: [], features: [], photos: ['https://picsum.photos/seed/CHERR01/800/600'], floorplans: []
    },
    {
        id: 'GRAPE00_PROP',
        address: { propertyName: 'Grapevine House', line1: '20 Grape Road', city: 'Cardiff', county: 'South Glamorgan', postcode: 'CF10 1DD', country: 'Wales' },
        tags: { rp: 'Bespoke Supportive Tenancies', supportProvider: 'ivolve', la: 'City and County of Cardiff' },
        region: 'Wales', serviceType: ServiceType.NursingCare, legalEntity: LegalEntity.Fieldbay, propertyType: 'Detached', livingType: 'Shared Living',
        handoverDate: '2019-09-09', handbackDate: null, flags: [],
        units: [
            { id: 'GRAPE00', name: 'Master', status: UnitStatus.Master }, { id: 'GRAPE01', name: 'Room 1', status: UnitStatus.Occupied },
            { id: 'GRAPE02', name: 'Room 2', status: UnitStatus.Occupied }, { id: 'GRAPE03', name: 'Room 3', status: UnitStatus.Occupied },
            { id: 'GRAPE04', name: 'Room 4', status: UnitStatus.Occupied },
        ],
        contacts: [], timeline: [], rentData: { currentSchedule: { year: '2024/25', documentUrl: '#', lines: [] }, previousSchedules: [], voidTerms: { initial: 'N/A', subsequent: 'N/A' } },
        maintenanceJobs: [], complianceItems: [], legalAgreements: [], documents: [], features: [], photos: ['https://picsum.photos/seed/GRAPE01/800/600'], floorplans: []
    },
    {
        id: 'PEAR01_PROP',
        address: { propertyName: 'The Pear Tree', line1: '1 Pear Tree Lane', city: 'Bristol', county: 'Avon', postcode: 'BS1 1EE', country: 'England' },
        tags: { rp: 'Inclusion Housing', supportProvider: 'ivolve', la: 'Bristol City Council' },
        region: 'South West', serviceType: ServiceType.SupportedLiving, legalEntity: LegalEntity.Heathcotes, propertyType: 'Bungalow', livingType: 'Self-contained',
        handoverDate: '2023-01-15', handbackDate: null, flags: [],
        units: [
            { id: 'PEAR01', name: 'The Bungalow', status: UnitStatus.Occupied },
        ],
        contacts: [], timeline: [], rentData: { currentSchedule: { year: '2024/25', documentUrl: '#', lines: [] }, previousSchedules: [], voidTerms: { initial: 'N/A', subsequent: 'N/A' } },
        maintenanceJobs: [], complianceItems: [], legalAgreements: [], documents: [], features: [], photos: ['https://picsum.photos/seed/PEAR01/800/600'], floorplans: []
    },
     {
        id: 'MANGO00_PROP',
        address: { propertyName: 'Mango Court', line1: '25 Mango Drive', city: 'Sheffield', county: 'South Yorkshire', postcode: 'S1 1FF', country: 'England' },
        tags: { rp: 'Harbour Light', supportProvider: 'ivolve', la: 'Sheffield City Council' },
        region: 'North', serviceType: ServiceType.Residential, legalEntity: LegalEntity.HeathcotesS, propertyType: 'Flat in property', livingType: 'Self-contained',
        handoverDate: '2017-08-12', handbackDate: '2024-08-31', flags: [],
        units: [
            { id: 'MANGO00', name: 'Master', status: UnitStatus.OutOfManagement }, { id: 'MANGO01', name: 'Flat 1', status: UnitStatus.OutOfManagement },
            { id: 'MANGO02', name: 'Flat 2', status: UnitStatus.OutOfManagement },
        ],
        contacts: [], timeline: [], rentData: { currentSchedule: { year: '2024/25', documentUrl: '#', lines: [] }, previousSchedules: [], voidTerms: { initial: 'N/A', subsequent: 'N/A' } },
        maintenanceJobs: [], complianceItems: [], legalAgreements: [], documents: [], features: [], photos: ['https://picsum.photos/seed/MANGO01/800/600'], floorplans: []
    },
    {
        id: 'STRAW00_PROP',
        address: { propertyName: 'Strawberry Fields', line1: '30 Strawberry Lane', city: 'Derby', county: 'Derbyshire', postcode: 'DE1 1GG', country: 'England' },
        tags: { rp: 'Bespoke Supportive Tenancies', supportProvider: 'ivolve', la: 'Derby City Council' },
        region: 'Midlands', serviceType: ServiceType.SupportedLiving, legalEntity: LegalEntity.Heathcotes, propertyType: 'Detached', livingType: 'Shared Living',
        handoverDate: '2022-04-01', handbackDate: null, flags: [],
        units: [
            { id: 'STRAW00', name: 'Master', status: UnitStatus.Master }, { id: 'STRAW01', name: 'Room 1', status: UnitStatus.Occupied },
            { id: 'STRAW02', name: 'Room 2', status: UnitStatus.Occupied }, { id: 'STRAW03', name: 'Room 3', status: UnitStatus.Occupied },
            { id: 'STRAW04', name: 'Sleep-in', status: UnitStatus.StaffSpace }, { id: 'STRAW05', name: 'Office', status: UnitStatus.StaffSpace },
        ],
        contacts: [], timeline: [], rentData: { currentSchedule: { year: '2024/25', documentUrl: '#', lines: [] }, previousSchedules: [], voidTerms: { initial: 'N/A', subsequent: 'N/A' } },
        maintenanceJobs: [], complianceItems: [], legalAgreements: [], documents: [], features: [], photos: ['https://picsum.photos/seed/STRAW01/800/600'], floorplans: []
    },
];

export const MOCK_PROPERTIES: Property[] = [
  {
    id: 'STRE00_PROP',
    address: {
      line1: '1 Street',
      city: 'Harrogate',
      county: 'North Yorkshire',
      postcode: 'HG1 1AA',
      country: 'England'
    },
    tags: {
      rp: 'Inclusion Housing',
      supportProvider: 'ivolve',
      la: 'North Yorkshire Council',
    },
    region: 'North',
    serviceType: ServiceType.SupportedLiving,
    legalEntity: LegalEntity.Heathcotes,
    propertyType: 'Terraced',
    livingType: 'Self-contained',
    handoverDate: '1995-01-01',
    handbackDate: null,
    flags: [
      { id: 'flag-1', message: 'Building site access – PPE required for all visits.', level: 'warning' }
    ],
    units: [
        { id: 'STRE00', name: 'Master', status: UnitStatus.Master },
        { id: 'STRE01', name: 'Flat 1', status: UnitStatus.Occupied },
        { id: 'STRE02', name: 'Flat 2', status: UnitStatus.Occupied, attention: true },
    ],
    contacts: [
      { id: 'c1', name: 'Jane Doe', role: 'Housing Officer', phone: '0161 123 4567', email: 'jane.doe@inclusion.com' },
      { id: 'c2', name: 'John Smith', role: 'Repairs Lead (ivolve)', phone: '07700 900123', email: 'john.s@ivolve.co.uk' },
    ],
    timeline: [
      { id: 't1', date: '2024-07-22', type: TimelineEventType.Compliance, description: 'Fire Risk Assessment posted. Next due: 2025-07-21.', actor: 'Admin' },
      { id: 't2', date: '2024-07-20', type: TimelineEventType.Repairs, description: 'Job #MCR-582 (Boiler) marked as Overdue.', actor: 'System' },
    ],
    rentData: {
      currentSchedule: {
        year: '2024/25',
        documentUrl: '/docs/rent-24-25.pdf',
        lines: [
          { category: 'Lease Rent', description: 'Base lease rent', amount: 500.00, period: 'week', rechargedToIvolve: true },
          { category: 'Core Rent', description: 'Tenant core rent', amount: 120.50, period: 'week', rechargedToIvolve: false },
        ],
      },
      previousSchedules: [],
      voidTerms: {
        initial: "Initial (Development) — Free period 90 days; Charges Lease Rent + Management Fee; Frequency every 4 weeks.",
        subsequent: "Subsequent (Operational) — Free period 28 days; Charges Core Rent only; Frequency weekly."
      }
    },
    maintenanceJobs: [
      {
        id: 'job-1', ref: 'HAR-582', propertyAddress: '1 Street, Harrogate', unit: 'Communal', category: 'Boiler Repair', nominalCode: NominalCode.BOI, priority: 'High', status: MaintenanceStatus.Assigned, reportedDate: '2024-07-10', slaDueDate: '2024-07-17', assignedTo: 'Yorkshire Sparks',
        details: { reportedBy: 'Tenant Unit 4', method: 'Phone', roomLocation: 'Boiler Room', summary: 'No hot water in building.', isTenantDamage: false, cost: { net: 150, vat: 30, gross: 180 } },
        activityLog: [
            { date: '2024-07-10', actor: 'Matt Fay', action: 'Job created.'},
            { date: '2024-07-11', actor: 'Matt Fay', action: 'Assigned to Yorkshire Sparks.'}
        ],
        jobType: 'Reactive',
      },
       {
        id: 'job-2', ref: 'HAR-583', propertyAddress: '1 Street, Harrogate', unit: 'Flat 2', category: 'Window Repair', nominalCode: NominalCode.WIN, priority: 'Medium', status: MaintenanceStatus.InProgress, reportedDate: '2024-07-15', slaDueDate: '2024-07-29', assignedTo: 'Midlands Property Care',
        details: { reportedBy: 'Housing Officer', method: 'Email', roomLocation: 'Living Room', summary: 'Window handle is broken and will not lock.', isTenantDamage: false, cost: { net: 0, vat: 0, gross: 0 } },
        activityLog: [
            { date: '2024-07-15', actor: 'Jenna Peters', action: 'Job created.'},
            { date: '2024-07-16', actor: 'Jenna Peters', action: 'Assigned to Midlands Property Care.'},
            { date: '2024-07-18', actor: 'Dave Smith (MPC)', action: 'Accepted job. Parts ordered, ETA 3 days.'}
        ],
        jobType: 'Reactive',
      },
      {
        id: 'job-3', ref: 'HAR-584', propertyAddress: '1 Street, Harrogate', unit: 'Communal', category: 'Gardening', nominalCode: NominalCode.GRD, priority: 'Low', status: MaintenanceStatus.Open, reportedDate: '2024-07-22', slaDueDate: '2024-08-19', assignedTo: '',
        details: { reportedBy: 'Area Manager', method: 'Email', roomLocation: 'Front Garden', summary: 'Hedges need trimming before next site visit.', isTenantDamage: false, cost: { net: 0, vat: 0, gross: 0 } },
        activityLog: [
            { date: '2024-07-22', actor: 'Clara Bell', action: 'Job created.'}
        ],
        jobType: 'Reactive',
      },
      {
        id: 'job-gs-1', ref: 'HAR-PPM-001', propertyAddress: '1 Street, Harrogate', unit: 'Communal', category: 'Gas Safety Inspection', nominalCode: NominalCode.BOI, priority: 'High', status: MaintenanceStatus.Open, reportedDate: '2025-04-14', slaDueDate: '2025-05-14', assignedTo: '',
        details: { reportedBy: 'System (PPM)', method: 'Email', roomLocation: 'Boiler Room', summary: 'Annual Gas Safety check automatically generated as per PPM schedule.', isTenantDamage: false, cost: { net: 0, vat: 0, gross: 0 } },
        activityLog: [
            { date: '2025-04-14', actor: 'System', action: 'Job auto-created from PPM Schedule "Annual Gas Safety Inspection"'}
        ],
        jobType: 'PPM',
        linkedComplianceId: 'comp-1',
      },
    ],
    complianceItems: [
      { id: 'comp-1', type: ComplianceType.GasSafety, lastCheck: '2024-05-15', nextCheck: '2025-05-14', status: 'Compliant', reportUrl: '/docs/gas-cert-24.pdf' },
      { id: 'comp-2', type: ComplianceType.EICR, lastCheck: '2022-08-01', nextCheck: '2027-07-31', status: 'Compliant', reportUrl: '/docs/eicr-22.pdf' },
      { id: 'comp-fra-1', type: ComplianceType.FireRiskAssessment, lastCheck: '2024-07-22', nextCheck: '2025-07-21', status: 'Compliant', reportUrl: '#' },
      { id: 'comp-epc-1', type: ComplianceType.EPC, lastCheck: '2021-09-01', nextCheck: '2031-08-31', status: 'Compliant', reportUrl: '#' },
      { id: 'comp-asb-1', type: ComplianceType.Asbestos, lastCheck: '2021-09-01', nextCheck: '2026-08-31', status: 'Compliant', reportUrl: '#' },
      { id: 'comp-fd-1', type: ComplianceType.FireDoor, lastCheck: '2024-07-22', nextCheck: '2025-01-22', status: 'Compliant', reportUrl: '#' },

    ],
    legalAgreements: [
      {
        id: 'legal-1', type: 'Lease', title: '25-Year FRI Lease with Inclusion Housing', date: '2021-09-01', documentUrl: '/docs/main-lease.pdf',
        clauses: [
          { id: 'cl-1', topic: 'Repairs', originalText: 'The Landlord shall be responsible for the maintenance, repair and renewal of the main structure of the Building...', plainText: 'The landlord must fix the building\'s main structure.', extraPlainText: 'Landlord fixes the important bits.' },
        ]
      }
    ],
    documents: MOCK_DOCS_STRE00,
    features: [],
    commissioning: {
        commissioner: MOCK_COMMISSIONERS.harrogate,
        hasWrittenSupport: true,
        documents: [
            { id: 'cd-1', name: 'Commissioner Letter of Support', url: '#' },
            { id: 'cd-2', name: 'Support Contract', url: '#' }
        ]
    },
    photos: ['https://picsum.photos/seed/prop1/800/600'],
    floorplans: ['httpsum.photos/seed/plan1/800/600'],
    linkedContacts: [
        { id: 'lc-1', role: 'RP Housing Officer', contactId: 'c-ih-ho1', stakeholderId: 'rp-ih' },
        { id: 'lc-2', role: 'ivolve Housing Lead', contactId: 'MF01' },
        { id: 'lc-3', role: 'LA Commissioner', contactId: 'c-hg', stakeholderId: 'la-nyc' },
    ],
    keyDates: MOCK_KEY_DATES_STRE00,
  },
  {
    id: 'EXAM00_PROP',
    address: {
      propertyName: 'Example House',
      line1: '123 Example Street',
      city: 'Nottingham',
      county: 'Nottinghamshire',
      postcode: 'NG1 1AJ',
      country: 'England'
    },
    tags: {
      rp: 'Harbour Light',
      supportProvider: 'ivolve',
      la: 'Nottingham City Council',
    },
    region: 'Midlands',
    serviceType: ServiceType.Residential,
    legalEntity: LegalEntity.HeathcotesM,
    propertyType: 'Semi-detached',
    livingType: 'Shared Living',
    handoverDate: '2000-02-01',
    handbackDate: null,
    flags: [],
    units: [
        { id: 'EXAM00', name: 'Master', status: UnitStatus.Master },
        { id: 'EXAM01', name: 'Room 1', status: UnitStatus.Occupied },
        { id: 'EXAM02', name: 'Room 2', status: UnitStatus.Void },
        { id: 'EXAM03', name: 'Room 3', status: UnitStatus.Occupied },
    ],
    contacts: [],
    timeline: [],
    rentData: {
      currentSchedule: { year: '2024/25', documentUrl: '#', lines: [] },
      previousSchedules: [],
      voidTerms: { initial: 'N/A', subsequent: 'N/A' }
    },
    maintenanceJobs: [
        {
            id: 'job-4', ref: 'NOT-101', propertyAddress: '123 Example Street, Nottingham', unit: 'Room 2', category: 'Full Redecoration', nominalCode: NominalCode.DEC, priority: 'Medium', status: MaintenanceStatus.AwaitingInvoice, reportedDate: '2024-06-20', slaDueDate: '2024-07-18', assignedTo: 'Midlands Property Care',
            details: { reportedBy: 'Daniel Evans', method: 'Email', roomLocation: 'Bedroom', summary: 'Void redecoration work. Paint walls magnolia, gloss skirting boards.', isTenantDamage: false, cost: { net: 400, vat: 80, gross: 480 } },
            activityLog: [
                { date: '2024-06-20', actor: 'Daniel Evans', action: 'Job created for void works.'},
                { date: '2024-06-21', actor: 'Daniel Evans', action: 'Assigned to Midlands Property Care.'},
                { date: '2024-07-05', actor: 'Dave Smith (MPC)', action: 'Work completed. Invoice to follow.'}
            ],
            jobType: 'Reactive',
        },
    ],
    complianceItems: [
        { id: 'comp-erd-1', type: ComplianceType.GasSafety, lastCheck: '2024-01-10', nextCheck: '2025-01-09', status: 'Compliant', reportUrl: '#' },
        { id: 'comp-erd-2', type: ComplianceType.FireRiskAssessment, lastCheck: '2023-08-15', nextCheck: '2024-08-14', status: 'Action Required', reportUrl: '#' },
        { id: 'comp-erd-3', type: ComplianceType.FireAlarm, lastCheck: '2024-02-01', nextCheck: '2025-01-31', status: 'Compliant', reportUrl: '#' },
    ],
    legalAgreements: [],
    documents: [],
    features: [],
    commissioning: {
        commissioner: MOCK_COMMISSIONERS.nottingham,
        hasWrittenSupport: false,
        documents: []
    },
    photos: ['httpsum.photos/seed/propERD1/800/600'],
    floorplans: [],
    keyDates: {},
  },
  {
    id: 'WALE01_PROP',
    address: {
      line1: '1 Welsh Road',
      city: 'Newport',
      county: 'Gwent',
      postcode: 'NP20 1DB',
      country: 'Wales',
    },
    tags: {
      rp: 'Bespoke Supportive Tenancies',
      supportProvider: 'ivolve',
      la: 'Newport City Council',
    },
    region: 'Wales',
    serviceType: ServiceType.NursingCare,
    legalEntity: LegalEntity.Fieldbay,
    propertyType: 'Bungalow',
    livingType: 'Shared Living',
    handoverDate: '2022-03-15',
    handbackDate: '2024-06-30',
    flags: [],
    units: [
      { id: 'WALE01', name: 'Master', status: UnitStatus.OutOfManagement },
      { id: 'WALE01-1', name: 'Room 1', status: UnitStatus.OutOfManagement },
      { id: 'WALE01-2', name: 'Room 2', status: UnitStatus.OutOfManagement },
      { id: 'WALE01-3', name: 'Room 3', status: UnitStatus.OutOfManagement },
      { id: 'WALE01-4', name: 'Room 4', status: UnitStatus.OutOfManagement },
      { id: 'WALE01-5', name: 'Room 5', status: UnitStatus.OutOfManagement },
    ],
    contacts: [],
    timeline: [],
    rentData: {
      currentSchedule: { year: '2024/25', documentUrl: '#', lines: [] },
      previousSchedules: [],
      voidTerms: { initial: 'N/A', subsequent: 'N/A' },
    },
    maintenanceJobs: [
      {
        id: 'job-5', ref: 'NEW-021', propertyAddress: '1 Welsh Road, Newport', unit: 'Communal', category: 'Leaking Pipe', nominalCode: NominalCode.PLM, priority: 'High', status: MaintenanceStatus.Completed, reportedDate: '2024-07-19', slaDueDate: '2024-07-20', assignedTo: 'Welsh Water Wizards',
        details: { reportedBy: 'On-site staff', method: 'Phone', roomLocation: 'Kitchen', summary: 'Pipe under sink is dripping water onto the floor.', isTenantDamage: false, cost: { net: 85, vat: 17, gross: 102 } },
        activityLog: [
            { date: '2024-07-19', actor: 'Matt Fay', action: 'Emergency job created.'},
            { date: '2024-07-19', actor: 'Matt Fay', action: 'Assigned to Welsh Water Wizards.'},
            { date: '2024-07-19', actor: 'Gareth Edwards (WWW)', action: 'On site. Isolated leak.'},
            { date: '2024-07-20', actor: 'Gareth Edwards (WWW)', action: 'Replaced pipe fitting. Leak resolved. Marked as complete.'}
        ],
        jobType: 'Reactive',
      },
    ],
    complianceItems: [
        { id: 'comp-wales-1', type: ComplianceType.GasSafety, lastCheck: '2023-07-30', nextCheck: '2024-07-29', status: 'Expired', reportUrl: '#' },
        { id: 'comp-wales-2', type: ComplianceType.LRA, lastCheck: '2023-07-30', nextCheck: '2024-07-29', status: 'Expired', reportUrl: '#' },
    ],
    legalAgreements: [],
    documents: [],
    features: [],
    commissioning: {
        commissioner: MOCK_COMMISSIONERS.newport,
        hasWrittenSupport: true,
        documents: [
            { id: 'cd-3', name: 'Nominations Agreement', url: '#' },
        ]
    },
    photos: ['httpsum.photos/seed/propWALE1/800/600'],
    floorplans: [],
    keyDates: {},
  },
  {
    id: 'CHES01_PROP',
    address: {
      line1: '33 High Street',
      city: 'Chester',
      county: 'Cheshire',
      postcode: 'CH1 1CH',
      country: 'England'
    },
    tags: {
      rp: 'Auckland Home Solutions',
      supportProvider: 'ivolve',
      la: 'Cheshire West and Chester Council',
    },
    region: 'North',
    serviceType: ServiceType.SupportedLiving,
    legalEntity: LegalEntity.Heathcotes,
    propertyType: 'Semi-detached',
    livingType: 'Shared Living',
    handoverDate: '2023-01-10',
    handbackDate: null,
    flags: [],
    units: [
        { id: 'CHES00', name: 'Master', status: UnitStatus.Master },
        { id: 'CHES01', name: 'Room 1', status: UnitStatus.Void },
        { id: 'CHES02', name: 'Room 2', status: UnitStatus.Occupied },
        { id: 'CHES03', name: 'Room 3', status: UnitStatus.Void },
        { id: 'CHES04', name: 'Room 4', status: UnitStatus.Void },
        { id: 'CHES05', name: 'Room 5', status: UnitStatus.Occupied },
        { id: 'CHES06', name: 'Room 6', status: UnitStatus.OutOfManagement },
    ],
    contacts: [],
    timeline: [],
    rentData: { currentSchedule: { year: '2024/25', documentUrl: '#', lines: [] }, previousSchedules: [], voidTerms: { initial: 'N/A', subsequent: 'N/A' }},
    maintenanceJobs: [],
    complianceItems: [
        { id: 'comp-ches-1', type: ComplianceType.GasSafety, lastCheck: '2024-08-01', nextCheck: '2025-07-31', status: 'Compliant', reportUrl: '#' },
    ],
    legalAgreements: [],
    documents: [],
    features: [],
    photos: ['httpsum.photos/seed/CHES01/800/600'],
    floorplans: [],
    keyDates: {},
  },
   {
    id: 'LIVP01_PROP',
    address: {
      propertyName: 'Scouse Tower',
      line1: '6 Low Street',
      city: 'Liverpool',
      county: 'Merseyside',
      postcode: 'L1 1LL',
      country: 'England'
    },
    tags: {
      rp: 'Harbour Light',
      supportProvider: 'ivolve',
      la: 'Liverpool City Council',
    },
    region: 'North',
    serviceType: ServiceType.SupportedLiving,
    legalEntity: LegalEntity.HeathcotesS,
    propertyType: 'Flat in property',
    livingType: 'Mixed',
    handoverDate: '2024-02-20',
    handbackDate: null,
    flags: [],
    units: [
        { id: 'LIVP00', name: 'Master', status: UnitStatus.Master },
        { id: 'LIVP01', name: 'Flat 1', status: UnitStatus.Occupied },
        { id: 'LIVP02', name: 'Flat 2', status: UnitStatus.Occupied },
        { id: 'LIVP03', name: 'Flat 3', status: UnitStatus.Void },
        { id: 'LIVP04', name: 'Flat 4', status: UnitStatus.Void },
        { id: 'LIVP05', 'name': 'Room 5', status: UnitStatus.Occupied }, // Shared
        { id: 'LIVP06', 'name': 'Room 6', status: UnitStatus.Occupied }, // Shared
        { id: 'LIVP07', 'name': 'Room 7', status: UnitStatus.Void },     // Shared
        { id: 'LIVP08', 'name': 'Room 8', status: UnitStatus.Void },     // Shared
        { id: 'LIVP09', name: 'Unit 9', status: UnitStatus.StaffSpace },
        { id: 'LIVP10', name: 'Flat 10', status: UnitStatus.Occupied },
        { id: 'LIVP11', name: 'Flat 11', status: UnitStatus.Occupied },
        { id: 'LIVP12', name: 'Flat 12', status: UnitStatus.Occupied },
        { id: 'LIVP13', name: 'Flat 13', status: UnitStatus.Void },
        { id: 'LIVP14', name: 'Flat 14', status: UnitStatus.Void },
        { id: 'LIVP15', name: 'Flat 15', status: UnitStatus.Occupied },
    ],
    contacts: [],
    timeline: [],
    rentData: { currentSchedule: { year: '2024/25', documentUrl: '#', lines: [] }, previousSchedules: [], voidTerms: { initial: 'N/A', subsequent: 'N/A' }},
    maintenanceJobs: [],
    complianceItems: [
        { id: 'comp-livp-1', type: ComplianceType.LiftLOLER, lastCheck: '2024-03-01', nextCheck: '2024-09-01', status: 'Compliant', reportUrl: '#' },
        { id: 'comp-livp-2', type: ComplianceType.EmergencyLighting, lastCheck: '2024-03-01', nextCheck: '2025-02-28', status: 'Compliant', reportUrl: '#' },
        { id: 'comp-livp-3', type: ComplianceType.Sprinkler, lastCheck: '2024-03-01', nextCheck: '2025-02-28', status: 'Compliant', reportUrl: '#' },
        { id: 'comp-livp-4', type: ComplianceType.FireAlarm, lastCheck: '2024-03-01', nextCheck: '2024-09-01', status: 'Compliant', reportUrl: '#' },
    ],
    legalAgreements: [],
    documents: [],
    features: [],
    photos: ['httpsum.photos/seed/LIVP01/800/600'],
    floorplans: [],
    keyDates: {},
  },
  ...MOCK_PROPERTIES_EXPANDED,
];

export const MOCK_STAKEHOLDERS: Stakeholder[] = [
    // Local Authorities
    {
        id: 'la-nyc',
        name: 'North Yorkshire Council',
        subName: 'Formerly Harrogate Borough Council',
        type: StakeholderType.LocalAuthority,
        website: 'https://www.northyorks.gov.uk/',
        logoComponent: 'NorthYorkshireLogo',
        about: "North Yorkshire Council is the local authority for North Yorkshire, England. It is a unitary authority, having taken over the functions of the previous county council and the seven district councils in April 2023. It provides a wide range of services to residents and businesses across the largest county in England.",
        address: { line1: 'County Hall', city: 'Northallerton', postcode: 'DL7 8AD' },
        keyInfo: [{ label: 'Area Covered', value: 'North Yorkshire' }],
        branding: { heroBg: 'bg-nyc-blue', heroText: 'text-white', cardBg: 'bg-nyc-blue', cardText: 'text-white' },
        contacts: [
            MOCK_COMMISSIONERS.harrogate,
            { id: 'c-hg-sw', name: 'Gemma Field', role: 'Social Worker', phone: '01423 500 600', email: 'g.field@northyorks.gov.uk' },
            { id: 'c-hg-dir', name: 'Richard Webb', role: 'Corporate Director', phone: '01609 780780', email: 'richard.webb@northyorks.gov.uk'}
        ]
    },
    {
        id: 'la-ncc',
        name: 'Nottingham City Council',
        type: StakeholderType.LocalAuthority,
        website: 'https://www.nottinghamcity.gov.uk/',
        logoComponent: 'NottinghamLogo',
        about: "Nottingham City Council is the unitary authority for the city of Nottingham. It provides all local government services for the city, including education, social care, housing, planning, and waste collection. The council is committed to making Nottingham a world-class city for its citizens, businesses, and visitors.",
        address: { line1: 'Loxley House', city: 'Nottingham', postcode: 'NG2 3NG' },
        keyInfo: [{ label: 'Council Type', value: 'Unitary Authority' }],
        branding: { heroBg: 'bg-notts-gray', heroText: 'text-white', cardBg: 'bg-notts-gray', cardText: 'text-white' },
        contacts: [
            MOCK_COMMISSIONERS.nottingham,
            { id: 'c-ng-dir', name: 'Catherine Underwood', role: 'Corporate Director for People Services', phone: '0115 915 5555', email: 'c.underwood@nottinghamcity.gov.uk'}
        ]
    },
    {
        id: 'la-npt',
        name: 'Newport City Council',
        subName: 'Cyngor Dinas Casnewydd',
        type: StakeholderType.LocalAuthority,
        website: 'https://www.newport.gov.uk/',
        logoComponent: 'NewportLogo',
        about: "Newport City Council (Cyngor Dinas Casnewydd) is the governing body for Newport, one of Wales' principal cities. It provides essential services to over 150,000 residents, focusing on community well-being, economic growth, and preserving the city's rich heritage.",
        address: { line1: 'Civic Centre', city: 'Newport', postcode: 'NP20 4UR' },
        keyInfo: [{ label: 'Country', value: 'Wales' }],
        branding: { heroBg: 'bg-white', heroText: 'text-newport-green', cardBg: 'bg-white', cardText: 'text-newport-green', cardBorder: 'border-newport-green' },
        contacts: [
            MOCK_COMMISSIONERS.newport,
            { id: 'c-np-sw', name: 'Cerys Williams', role: 'Social Worker', phone: '01633 656 656', email: 'c.williams@newport.gov.uk' },
        ]
    },
     {
        id: 'la-cwc',
        name: 'Cheshire West and Chester Council',
        type: StakeholderType.LocalAuthority,
        website: 'https://www.cheshirewestandchester.gov.uk/',
        branding: { heroBg: 'bg-gray-800', heroText: 'text-white', cardBg: 'bg-gray-800', cardText: 'text-white' },
        contacts: []
    },
    { id: 'la-leeds', name: 'Leeds City Council', type: StakeholderType.LocalAuthority, branding: { heroBg: 'bg-blue-800', heroText: 'text-white', cardBg: 'bg-blue-800', cardText: 'text-white' }, contacts: [] },
    { id: 'la-manc', name: 'Manchester City Council', type: StakeholderType.LocalAuthority, branding: { heroBg: 'bg-yellow-400', heroText: 'text-black', cardBg: 'bg-yellow-400', cardText: 'text-black' }, contacts: [] },
    { id: 'la-birm', name: 'Birmingham City Council', type: StakeholderType.LocalAuthority, branding: { heroBg: 'bg-purple-900', heroText: 'text-white', cardBg: 'bg-purple-900', cardText: 'text-white' }, contacts: [] },
    { id: 'la-cardiff', name: 'City and County of Cardiff', type: StakeholderType.LocalAuthority, branding: { heroBg: 'bg-sky-700', heroText: 'text-white', cardBg: 'bg-sky-700', cardText: 'text-white' }, contacts: [] },
    { id: 'la-bristol', name: 'Bristol City Council', type: StakeholderType.LocalAuthority, branding: { heroBg: 'bg-teal-700', heroText: 'text-white', cardBg: 'bg-teal-700', cardText: 'text-white' }, contacts: [] },
    { id: 'la-sheff', name: 'Sheffield City Council', type: StakeholderType.LocalAuthority, branding: { heroBg: 'bg-red-700', heroText: 'text-white', cardBg: 'bg-red-700', cardText: 'text-white' }, contacts: [] },
    { id: 'la-derby', name: 'Derby City Council', type: StakeholderType.LocalAuthority, branding: { heroBg: 'bg-gray-900', heroText: 'text-white', cardBg: 'bg-gray-900', cardText: 'text-white' }, contacts: [] },

    // Registered Providers
    {
        id: 'rp-ih',
        name: 'Inclusion Housing',
        type: StakeholderType.RegisteredProvider,
        website: 'https://www.inclusion-group.org.uk/inclusion-housing/',
        logoComponent: 'InclusionLogo',
        about: "Inclusion Housing is a social enterprise and registered provider of social housing. They work with a range of vulnerable people, including those with learning disabilities, mental ill-health, and older people, providing quality homes with care and support to help them live more independently.",
        address: { line1: '10 Audax Court, Audax Road', city: 'York', postcode: 'YO30 4RB' },
        keyInfo: [
            { label: 'Company No.', value: '06169583' }, 
            { label: 'Regulator of Social Housing No.', value: '4637' }
        ],
        branding: { heroBg: 'bg-white', heroText: 'text-black', cardBg: 'bg-status-red', cardText: 'text-white', cardBorder: 'border-gray-400' },
        contacts: [ 
            // Tier 1: General
            { id: 'c-ih-gen1', name: 'General Enquiries', role: 'Main Office', phone: '01904 675207', email: 'info@inclusionhousing.org.uk', tier: ContactTier.General },
            { id: 'c-ih-gen2', name: 'Repairs Hotline', role: 'Facilities Desk', phone: '01904 675208', email: 'repairs@inclusionhousing.org.uk', tier: ContactTier.General },
            // Tier 2: Executive
            { id: 'c-ih-exec1', name: 'Michelle Dodgson', role: 'Chief Executive Officer', phone: '01904 675207', email: 'm.dodgson@inclusionhousing.org.uk', tier: ContactTier.Executive, isPinned: true },
            { id: 'c-ih-exec2', name: 'Neil Brown', role: 'Chair of the Board', phone: '01904 675207', email: 'n.brown@inclusionhousing.org.uk', tier: ContactTier.Executive },
            // Tier 3: Senior Management
            { id: 'c-ih-sm1', name: 'Sarah Thompson', role: 'Head of Housing', phone: '01904 675210', email: 's.thompson@inclusionhousing.org.uk', tier: ContactTier.SeniorManagement },
            // Tier 4: Housing Officers
            { id: 'c-ih-ho1', name: 'David Miller', role: 'Housing Officer (North)', phone: '07711 223344', email: 'd.miller@inclusionhousing.org.uk', tier: ContactTier.Operations },
            // Tier 5: Finance
            { id: 'c-ih-fin1', name: 'Finance Team', role: 'Accounts Payable', phone: '01904 675220', email: 'finance@inclusionhousing.org.uk', tier: ContactTier.Finance },
        ]
    },
    {
        id: 'rp-hl',
        name: 'Harbour Light',
        type: StakeholderType.RegisteredProvider,
        website: 'https://harbourlight.org.uk/',
        logoComponent: 'HarbourLightLogo',
        about: "Harbour Light is an exempt-accommodation provider that supports vulnerable adults to live independently. They aim to deliver quality housing and support services, fostering a safe and empowering environment for their tenants.",
        address: { line1: 'Suite 2A, The Quadrant', city: 'Sheffield', postcode: 'S2 5SY' },
        keyInfo: [{ label: 'Status', value: 'Community Interest Company' }],
        branding: { heroBg: 'bg-rp-harbour-bg', heroText: 'text-rp-harbour-text', cardBg: 'bg-rp-harbour-text', cardText: 'text-white', cardBorder: 'border-rp-harbour-text' },
        contacts: [
            {id: 'c-hl-gen1', name: 'Main Office', role: 'Enquiries', phone: '0114 278 7575', email: 'info@harbourlight.org.uk', tier: ContactTier.General},
            {id: 'c-hl-exec1', name: 'Peter George', role: 'Managing Director', phone: '0114 278 7575', email: 'p.george@harbourlight.org.uk', tier: ContactTier.Executive},
            {id: 'c-hl-ops1', name: 'Angelarinsic', role: 'Housing Manager', phone: '07812 345678', email: 'a.angela@harbourlight.org.uk', tier: ContactTier.Operations}
        ]
    },
    {
        id: 'rp-best',
        name: 'Bespoke Supportive Tenancies',
        subName: '(BeST)',
        type: StakeholderType.RegisteredProvider,
        website: 'https://www.bestha.co.uk/',
        logoComponent: 'BeSTLogo',
        about: "Bespoke Supportive Tenancies (BeST) is a Community Benefit Society and Registered Provider of Social Housing. They specialise in providing bespoke housing solutions for individuals with learning disabilities, autism, and mental health needs, ensuring tenants have a home for life.",
        address: { line1: 'Suite 3, The Stables, Little Droitwich', city: 'Droitwich Spa', postcode: 'WR9 0BZ' },
        keyInfo: [
            { label: 'Community Benefit Society No.', value: '7538' }, 
            { label: 'Regulator of Social Housing No.', value: '4831' }
        ],
        branding: { heroBg: 'bg-best-purple', heroText: 'text-white', cardBg: 'bg-best-green', cardText: 'text-best-purple', cardBorder: 'border-best-purple' },
        contacts: [
             {id: 'c-best-gen1', name: 'Main Office', role: 'Enquiries', phone: '0121 445 4648', email: 'info@bestha.co.uk', tier: ContactTier.General},
             {id: 'c-best-exec1', name: 'Paul de Savary', role: 'Chief Executive', phone: '0121 445 4648', email: 'p.desavary@bestha.co.uk', tier: ContactTier.Executive},
             {id: 'c-best-ops1', name: 'Gail Corden', role: 'Housing Manager', phone: '07701 987654', email: 'g.corden@bestha.co.uk', tier: ContactTier.Operations}
        ]
    },
    {
        id: 'rp-ahs',
        name: 'Auckland Home Solutions',
        type: StakeholderType.RegisteredProvider,
        website: '#',
        logoComponent: '',
        branding: { heroBg: 'bg-gray-700', heroText: 'text-white', cardBg: 'bg-gray-200', cardText: 'text-gray-800', cardBorder: 'border-gray-400' },
        contacts: [
            {id: 'c-ahs-1', name: 'Main Office', role: 'Enquiries', phone: '01388 606 606', email: 'info@aucklandhs.co.uk', tier: ContactTier.General},
        ]
    },
    // Contractors
    {
        id: 'co-1',
        name: 'Midlands Property Care',
        type: StakeholderType.Contractor,
        areaOfOperation: 'Midlands',
        trades: [ContractorTrade.General, ContractorTrade.Decorator, ContractorTrade.Gardener],
        branding: { heroBg: '', heroText: '', cardBg: '', cardText: '' },
        contacts: [ {id: 'c-mpc1', name: 'Dave Smith', role: 'Manager', phone: '0121 456 7890', email: 'dave@mpc.com'} ],
    },
    {
        id: 'co-2',
        name: 'Yorkshire Sparks',
        type: StakeholderType.Contractor,
        areaOfOperation: 'North',
        trades: [ContractorTrade.Electrician],
        branding: { heroBg: '', heroText: '', cardBg: '', cardText: '' },
        contacts: [ {id: 'c-ys1', name: 'Sarah Jenkins', role: 'Lead Electrician', phone: '0113 987 6543', email: 's.jenkins@ysparks.co.uk'} ],
    },
    {
        id: 'co-3',
        name: 'Welsh Water Wizards',
        type: StakeholderType.Contractor,
        areaOfOperation: 'Wales',
        trades: [ContractorTrade.Plumber],
        branding: { heroBg: '', heroText: '', cardBg: '', cardText: '' },
        contacts: [ {id: 'c-www1', name: 'Gareth Edwards', role: 'Owner', phone: '029 2000 1122', email: 'g.edwards@waterwizards.wales'} ],
    },
    // Developers
    {
        id: 'dev-1',
        name: 'Oak Frame Developments',
        type: StakeholderType.Developer,
        website: '#',
        branding: { heroBg: 'bg-amber-800', heroText: 'text-white', cardBg: 'bg-amber-800', cardText: 'text-white' },
        contacts: [],
    },
    // Landlords
    {
        id: 'll-1',
        name: 'Mr. John Landlord',
        type: StakeholderType.Landlord,
        branding: { heroBg: 'bg-gray-200', heroText: 'text-black', cardBg: 'bg-gray-200', cardText: 'text-black' },
        contacts: [{id: 'c-ll1', name: 'Mr. John Landlord', role: 'Owner', phone: '07777 123456', email: 'j.landlord@email.com'}],
    }
];

export const MOCK_IVOLVE_STAFF: IvolveStaff[] = [
    // Board
    { id: 'IM01', name: 'Ian McKay', role: 'Chairman', email: 'i.mckay@ivolve.co.uk', phone: '07700900001', managerId: null, team: 'Board of Directors', tags: ['Board'], relevance: 1 },
    
    // Executive Team
    { id: 'TD01', name: 'Leo Vance', role: 'Group Chief Executive Officer', email: 'l.vance@ivolve.co.uk', phone: '07700900100', managerId: 'IM01', team: 'Executive Team', tags: ['Executive', 'Director'], relevance: 5, isPinned: true },
    { id: 'NR01', name: 'Olivia Chen', role: 'Chief Financial Officer', email: 'o.chen@ivolve.co.uk', phone: '07700900101', managerId: 'TD01', team: 'Finance Team', tags: ['Executive', 'Director'], relevance: 5 },
    { id: 'KG01', name: 'Ben Carter', role: 'Chief People Officer', email: 'b.carter@ivolve.co.uk', phone: '07700900102', managerId: 'TD01', team: 'People Team', tags: ['Executive', 'Director'], relevance: 5 },
    { id: 'LH01', name: 'Sophia Wells', role: 'Managing Director, England', email: 's.wells@ivolve.co.uk', phone: '07700900103', managerId: 'TD01', team: 'Operational Team', tags: ['Executive', 'Director', 'England'], relevance: 5 },
    { id: 'GFH01', name: 'Graham Foster', role: 'Chief Quality Officer', email: 'g.foster@ivolve.co.uk', phone: '07700900104', managerId: 'TD01', team: 'Quality Team', tags: ['Executive', 'Director'], relevance: 5 },
    { id: 'CC01', name: 'Chloe Anderson', role: 'Commercial Director', email: 'c.anderson@ivolve.co.uk', phone: '07700900105', managerId: 'TD01', team: 'Commercial Team', tags: ['Executive', 'Director'], relevance: 5 },

    // Property Team
    { id: 'CG01', name: 'Craig Morgan', role: 'Group Director of Property', email: 'c.morgan@ivolve.co.uk', phone: '07700900200', managerId: 'TD01', team: 'Property Team', tags: ['Central Functions', 'Director'], relevance: 10, isPinned: true },
    { id: 'MF01', name: 'Matt Fay', role: 'Housing Partnerships and Operations Manager', email: 'm.fay@ivolve.co.uk', phone: '07700900201', managerId: 'CG01', team: 'Property Team', tags: ['Central Functions', 'BeST', 'Inclusion', 'Harbour Light', 'Property Team', 'Function Lead'], relevance: 100, 
      personalizationIcons: [
        { id: '1', name: 'dog', color: '#f97316' },
        { id: '2', name: 'piano', color: '#8b5cf6' },
      ], 
      cardTemplate: 'white' 
    },
    { id: 'AS01', name: 'Aaron Banks', role: 'Group Head of Facilities and Services', email: 'a.banks@ivolve.co.uk', phone: '07700900202', managerId: 'CG01', team: 'Property Team', tags: ['Facilities', 'Services', 'Function Lead'], relevance: 8 },
    { id: 'MP01', name: 'Megan Parker', role: 'Property Hub Manager', email: 'm.parker@ivolve.co.uk', phone: '07700900203', managerId: 'AS01', team: 'Property Team', tags: ['Property Hub', 'Manager'], relevance: 8 },
    { id: 'VM01', name: 'Vacancy', role: 'Facilities Manager - Wales', email: '', phone: '', managerId: 'CG01', team: 'Property Team', tags: ['Wales', 'Facilities', 'Manager'], isVacancy: true, relevance: 1 },
    { id: 'JS01', name: 'Jenna Peters', role: 'Housing Officer', email: 'j.peters@ivolve.co.uk', phone: '07700900205', managerId: 'MF01', team: 'Property Team', tags: ['Housing', 'North'], relevance: 9 },
    { id: 'DA01', name: 'Daniel Evans', role: 'Housing Officer', email: 'd.evans@ivolve.co.uk', phone: '07700900206', managerId: 'MF01', team: 'Property Team', tags: ['Housing', 'Midlands'], relevance: 9 },

    // Finance Team
    { id: 'KD01', name: 'Karen Dunn', role: 'Group Finance Director', email: 'k.dunn@ivolve.co.uk', phone: '07700900300', managerId: 'NR01', team: 'Finance Team', tags: ['Director'], relevance: 4 },
    { id: 'SW01', name: 'Sam Wallace', role: 'Group FP & A Manager', email: 's.wallace@ivolve.co.uk', phone: '07700900301', managerId: 'KD01', team: 'Finance Team', tags: ['Manager'], relevance: 3 },
    { id: 'AT01', name: 'Alice Thompson', role: 'Commercial Finance Lead', email: 'a.thompson@ivolve.co.uk', phone: '07700900302', managerId: 'KD01', team: 'Finance Team', tags: ['Function Lead'], relevance: 3 },
    { id: 'JS02', name: 'Joining Soon', role: 'Management Accountant', email: '', phone: '', managerId: 'SW01', team: 'Finance Team', tags: [], isJoiningSoon: true, relevance: 1 },

    // Operations
    { id: 'GH01', name: 'Grace Hill', role: 'Operations Director, Region 1 North', email: 'g.hill@ivolve.co.uk', phone: '07700900400', managerId: 'LH01', team: 'Operational Team', tags: ['North', 'Region 1', 'Director'], relevance: 4 },
    { id: 'HD01', name: 'Harry Doyle', role: 'Operations Director, Region 1 Midlands', email: 'h.doyle@ivolve.co.uk', phone: '07700900401', managerId: 'LH01', team: 'Operational Team', tags: ['Midlands', 'Region 1', 'Director'], relevance: 4 },
    { id: 'JM01', name: 'Jack Murphy', role: 'Area Manager - Notts & Newark', email: 'j.murphy@ivolve.co.uk', phone: '07700900402', managerId: 'HD01', team: 'Operational Team', tags: ['Nottinghamshire', 'Newark', 'Area Manager'], relevance: 2 },
    { id: 'CB01', name: 'Clara Bell', role: 'Area Manager - East Coast & Leeds', email: 'c.bell@ivolve.co.uk', phone: '07700900403', managerId: 'GH01', team: 'Operational Team', tags: ['East Coast', 'Leeds', 'Area Manager'], relevance: 2 },
    { id: 'NH01', name: 'Nora Hayes', role: 'Team Leader - Notts & Lincoln', email: 'n.hayes@ivolve.co.uk', phone: '07700900404', managerId: 'JM01', team: 'Operational Team', tags: ['STRE00_PROP', 'Team Leader'], relevance: 3 },
    
    // People Team
    { id: 'TM01', name: 'Tara Mason', role: 'Group Head of People', email: 't.mason@ivolve.co.uk', phone: '07700900500', managerId: 'KG01', team: 'People Team', tags: ['Function Lead'], relevance: 4 },

    // IT Team
    { id: 'KH01', name: 'Kevin Hall', role: 'Group IT Director', email: 'k.hall@ivolve.co.uk', phone: '07700900600', managerId: 'TD01', team: 'IT Team', tags: ['Director'], relevance: 4 },

    // Learning and Development
    { id: 'JW01', name: 'Julia Wright', role: 'Group Head of L&D', email: 'j.wright@ivolve.co.uk', phone: '07700900700', managerId: 'KG01', team: 'Learning and Development Team', tags: ['Function Lead'], relevance: 4 },
    
    // Business Development
    { id: 'RL01', name: 'Rachel Lewis', role: 'Group Head of Growth & Development', email: 'r.lewis@ivolve.co.uk', phone: '07700900800', managerId: 'CC01', team: 'Business Development Team', tags: ['Function Lead'], relevance: 4 },
];

const MOCK_APPLICANTS: Person[] = [
    {
        id: 'APP001', preferredFirstName: 'Sarah', legalFirstName: 'Sarah', surname: 'Jenkins', 
        dob: '1995-08-20', status: PersonStatus.Applicant,
        propertyId: '', unitId: '', moveInDate: '', moveOutDate: null,
        keyWorkerId: '', areaManagerId: '',
        careNeeds: [{ id: 'cn-app1', category: 'Primary Need', detail: 'Autism Spectrum Disorder' }],
        funding: [], tenancy: { type: 'Licence Agreement', startDate: '', documents: [] },
        timeline: [], documents: [], contacts: [], title: 'Miss', firstLanguage: 'English', isNonVerbal: false,
        applicationStage: ApplicationStage.Referral,
        referralDate: '2024-07-28',
        referralSource: 'North Yorkshire Council',
        preferredServiceType: ServiceType.SupportedLiving,
        preferredRegion: 'North',
        potentialRp: 'Inclusion Housing',
    },
    {
        id: 'APP002', preferredFirstName: 'Tom', legalFirstName: 'Thomas', surname: 'Baker', 
        dob: '1988-03-15', status: PersonStatus.Applicant,
        propertyId: '', unitId: '', moveInDate: '', moveOutDate: null,
        keyWorkerId: '', areaManagerId: '',
        careNeeds: [{ id: 'cn-app2', category: 'Primary Need', detail: 'Complex Mental Health' }],
        funding: [], tenancy: { type: 'Licence Agreement', startDate: '', documents: [] },
        timeline: [], documents: [], contacts: [], title: 'Mr', firstLanguage: 'English', isNonVerbal: false,
        applicationStage: ApplicationStage.Application,
        referralDate: '2024-07-25',
        referralSource: 'Nottingham City Council',
        preferredServiceType: ServiceType.Residential,
        preferredRegion: 'Midlands',
        potentialRp: 'Harbour Light',
    },
    {
        id: 'APP003', preferredFirstName: 'Chloe', legalFirstName: 'Chloe', surname: 'Davies', 
        dob: '2001-11-02', status: PersonStatus.Applicant,
        propertyId: '', unitId: '', moveInDate: '', moveOutDate: null,
        keyWorkerId: '', areaManagerId: '',
        careNeeds: [{ id: 'cn-app3', category: 'Primary Need', detail: 'Learning Disability' }],
        funding: [], tenancy: { type: 'Licence Agreement', startDate: '', documents: [] },
        timeline: [], documents: [], contacts: [], title: 'Miss', firstLanguage: 'English', isNonVerbal: false,
        applicationStage: ApplicationStage.Application,
        referralDate: '2024-07-22',
        referralSource: 'Self-referral',
        preferredServiceType: ServiceType.SupportedLiving,
        preferredRegion: 'Wales',
        potentialRp: 'Bespoke Supportive Tenancies',
    },
    {
        id: 'APP004', preferredFirstName: 'Mike', legalFirstName: 'Michael', surname: 'Rodriguez', 
        dob: '1992-01-30', status: PersonStatus.Applicant,
        propertyId: '', unitId: '', moveInDate: '', moveOutDate: null,
        keyWorkerId: '', areaManagerId: '',
        careNeeds: [{ id: 'cn-app4', category: 'Primary Need', detail: 'Physical Disability' }],
        funding: [], tenancy: { type: 'Licence Agreement', startDate: '', documents: [] },
        timeline: [], documents: [], contacts: [], title: 'Mr', firstLanguage: 'English', isNonVerbal: false,
        applicationStage: ApplicationStage.AwaitingProperty,
        referralDate: '2024-06-15',
        referralSource: 'Manchester City Council',
        preferredServiceType: ServiceType.SupportedLiving,
        preferredRegion: 'North',
    },
    {
        id: 'APP005', preferredFirstName: 'Aisha', legalFirstName: 'Aisha', surname: 'Khan', 
        dob: '1999-09-09', status: PersonStatus.Applicant,
        propertyId: 'APPLE00_PROP', unitId: '', moveInDate: '', moveOutDate: null,
        keyWorkerId: '', areaManagerId: '',
        careNeeds: [{ id: 'cn-app5', category: 'Primary Need', detail: 'Learning Disability' }],
        funding: [], tenancy: { type: 'Licence Agreement', startDate: '', documents: [] },
        timeline: [], documents: [], contacts: [], title: 'Miss', firstLanguage: 'English', isNonVerbal: false,
        applicationStage: ApplicationStage.PropertyMatched,
        referralDate: '2024-05-20',
        referralSource: 'Leeds City Council',
        preferredServiceType: ServiceType.SupportedLiving,
        preferredRegion: 'North',
        potentialRp: 'Inclusion Housing',
    },
];

export const MOCK_PEOPLE: Person[] = [
    // 1 Street, Harrogate
    {
        id: 'P001', preferredFirstName: 'Alice', legalFirstName: 'Alice', surname: 'Johnson', dob: '1992-05-15', status: PersonStatus.Current,
        propertyId: 'STRE00_PROP', unitId: 'STRE01', moveInDate: '2022-01-20', moveOutDate: null,
        keyWorkerId: 'NH01', areaManagerId: 'CB01',
        careNeeds: [
            { id: 'cn1', category: 'Mobility', detail: 'Requires assistance with stairs.' },
            { id: 'cn2', category: 'Medication', detail: 'Prompting required for morning medication.' },
        ],
        funding: [{ id: 'fund-p1-1', source: 'North Yorkshire Council', weeklyAmount: 850.00, details: 'Personal Independence Payment (PIP) and Housing Benefit.' }],
        tenancy: { type: 'Licence Agreement', startDate: '2022-01-20', documents: [{ id: 'doc-p1-1', name: 'Alice J - Licence Agreement', type: 'PDF', date: '2022-01-20', year: 2022, url: '#'}] },
        timeline: [
            { id: 'pt1-1', date: '2024-07-15', type: TimelineEventType.Care, description: 'Annual support plan review completed.', actor: 'Nora Hayes' },
        ],
        documents: [
             { id: 'doc-p1-1', name: 'Alice J - Licence Agreement', type: 'PDF', date: '2022-01-20', year: 2022, url: '#'},
             { id: 'doc-p1-2', name: 'Support Plan Review 2024', type: 'PDF', date: '2024-07-15', year: 2024, url: '#'},
        ],
        contacts: [],
        title: 'Miss', firstLanguage: 'English', isNonVerbal: false, maritalStatus: 'Single', ethnicity: 'White British', nationality: 'British', nationalInsuranceNumber: 'AB123456C',
        email: 'alice.j@example.com', phone: '07712 345678',
        allergies: ['Penicillin', 'Dust Mites'],
        medicalConditions: ['Asthma', 'Type 2 Diabetes'],
        medications: [
            { id: 'med-1', name: 'Metformin', dosage: '500mg', frequency: 'Twice daily', notes: 'Take with food.' },
            { id: 'med-2', name: 'Salbutamol Inhaler', dosage: '100mcg', frequency: 'As needed', notes: 'For asthma symptoms.' }
        ],
        pets: 'A cat named Mittens.',
        hasCapacityToConsent: true,
        rightToResideStatus: 'Full UK Citizen',
        managesOwnMoney: true,
        hasSmiExemption: false,
        housingBenefitRefNumber: 'HB-AJ-12345',
        housingBenefitCouncil: 'North Yorkshire Council',
        housingBenefitAmount: 110.00,
        benefits: [
            { type: BenefitType.UCStandard, amount: 95.50, frequency: 'Weekly', startDate: '2022-01-20' },
            { type: BenefitType.PIPCare, amount: 68.10, frequency: 'Weekly', startDate: '2022-01-20' },
            { type: BenefitType.PIPMobility, amount: 26.90, frequency: 'Weekly', startDate: '2023-05-10' },
        ],
        savingsInfo: 'Has a savings account with approximately £2,500. No other significant assets.',
    },
    {
        id: 'P002', preferredFirstName: 'Ben', legalFirstName: 'Benjamin', surname: 'Williams', dob: '1988-11-30', status: PersonStatus.Current,
        propertyId: 'STRE00_PROP', unitId: 'STRE02', moveInDate: '2021-09-01', moveOutDate: null,
        keyWorkerId: 'NH01', areaManagerId: 'CB01',
        careNeeds: [{ id: 'cn3', category: 'Social Engagement', detail: 'Support to attend weekly community group.' }],
        funding: [{ id: 'fund-p2-1', source: 'NHS CCG', weeklyAmount: 920.50, details: 'Continuing Healthcare funding package.' }],
        tenancy: { type: 'Licence Agreement', startDate: '2021-09-01', documents: [] },
        timeline: [], documents: [],
        contacts: [],
        title: 'Mr', firstLanguage: 'English', isNonVerbal: false, nationalInsuranceNumber: 'CD789012D',
        flags: [{id: 'flag-p2-1', message: 'High risk of falls. Please ensure clear pathways and use of walking frame.', level: 'danger'}]
    },
    // 123 Example Street, Nottingham
    {
        id: 'P003', preferredFirstName: 'Chloe', legalFirstName: 'Chloe', surname: 'Davis', dob: '2001-02-10', status: PersonStatus.Current,
        propertyId: 'EXAM00_PROP', unitId: 'EXAM01', moveInDate: '2023-08-01', moveOutDate: null,
        keyWorkerId: 'NH01', areaManagerId: 'JM01',
        careNeeds: [], 
        funding: [{ id: 'fund-p3-1', source: 'Nottingham City Council', weeklyAmount: 780.00, details: '' }],
        tenancy: { type: 'Assured Shorthold Tenancy', startDate: '2023-08-01', documents: [] },
        timeline: [], documents: [],
        contacts: [],
        title: '', firstLanguage: 'English', isNonVerbal: false
    },
    {
        id: 'P004', preferredFirstName: 'Daniel', legalFirstName: 'Daniel', surname: 'Miller', dob: '1995-07-22', status: PersonStatus.Former,
        propertyId: 'EXAM00_PROP', unitId: 'EXAM02', moveInDate: '2022-05-10', moveOutDate: '2024-06-15',
        keyWorkerId: 'NH01', areaManagerId: 'JM01',
        careNeeds: [], 
        funding: [{ id: 'fund-p4-1', source: 'Nottingham City Council', weeklyAmount: 750.00, details: '' }],
        tenancy: { type: 'Assured Shorthold Tenancy', startDate: '2022-05-10', documents: [] },
        timeline: [
            { id: 'pt4-1', date: '2024-06-15', type: TimelineEventType.Moves, description: 'Moved out to independent living property.', actor: 'Daniel Evans' },
        ],
        documents: [],
        contacts: [],
        title: 'Mr', firstLanguage: 'English', isNonVerbal: false
    },
    {
        id: 'P005', preferredFirstName: 'Emily', legalFirstName: 'Emily', surname: 'Brown', dob: '1999-01-05', status: PersonStatus.Current,
        propertyId: 'EXAM00_PROP', unitId: 'EXAM03', moveInDate: '2024-03-12', moveOutDate: null,
        keyWorkerId: 'NH01', areaManagerId: 'JM01',
        careNeeds: [], 
        funding: [{ id: 'fund-p5-1', source: 'Personal Budget', weeklyAmount: 650.00, details: '' }],
        tenancy: { type: 'Assured Shorthold Tenancy', startDate: '2024-03-12', documents: [] },
        timeline: [], documents: [],
        contacts: [],
        title: 'Mrs', firstLanguage: 'BSL', isNonVerbal: true,
        flags: [{id: 'flag-p5-1', message: 'Family visit scheduled for next Tuesday. Please ensure communal areas are tidy.', level: 'warning'}]
    },
     // 1 Welsh Road, Newport
    {
        id: 'P006', preferredFirstName: 'Ffion', legalFirstName: 'Ffion', surname: 'Morgan', dob: '1985-03-01', status: PersonStatus.Former,
        propertyId: 'WALE01_PROP', unitId: 'WALE01-1', moveInDate: '2022-03-15', moveOutDate: '2024-06-30',
        keyWorkerId: 'NH01', areaManagerId: 'HD01', // Placeholder manager
        careNeeds: [], 
        funding: [{ id: 'fund-p6-1', source: 'Newport City Council', weeklyAmount: 1100.00, details: '' }],
        tenancy: { type: 'Licence Agreement', startDate: '2022-03-15', documents: [] },
        timeline: [], documents: [],
        contacts: [],
        title: 'Miss', firstLanguage: 'Welsh', secondLanguage: 'English', isNonVerbal: false
    },
    {
        id: 'P007', preferredFirstName: 'Gareth', legalFirstName: 'Gareth', surname: 'Price', dob: '1990-09-18', status: PersonStatus.Former,
        propertyId: 'WALE01_PROP', unitId: 'WALE01-2', moveInDate: '2022-04-01', moveOutDate: '2024-06-30',
        keyWorkerId: 'NH01', areaManagerId: 'HD01',
        careNeeds: [], 
        funding: [{ id: 'fund-p7-1', source: 'Newport City Council', weeklyAmount: 1100.00, details: '' }],
        tenancy: { type: 'Licence Agreement', startDate: '2022-04-01', documents: [] },
        timeline: [], documents: [],
        contacts: [],
        title: 'Mr', firstLanguage: 'English', isNonVerbal: false
    },
    {
        id: 'P008', preferredFirstName: 'Harri', legalFirstName: 'Harri', surname: 'Jenkins', dob: '1998-12-07', status: PersonStatus.Former,
        propertyId: 'WALE01_PROP', unitId: 'WALE01-4', moveInDate: '2023-01-20', moveOutDate: '2024-06-30',
        keyWorkerId: 'NH01', areaManagerId: 'HD01',
        careNeeds: [], 
        funding: [{ id: 'fund-p8-1', source: 'Newport City Council', weeklyAmount: 1100.00, details: '' }],
        tenancy: { type: 'Licence Agreement', startDate: '2023-01-20', documents: [] },
        timeline: [], documents: [],
        contacts: [],
        title: 'Mr', firstLanguage: 'English', isNonVerbal: false
    },
    // New people for new properties
// FIX: Added the required 'contacts' property to the mapped object and ensured the funding property is an array.
    ...[
        { id: 'P009', unitId: 'APPLE01', firstName: 'Ian', lastName: 'Taylor', dob: '1994-03-12' },
        { id: 'P010', unitId: 'APPLE02', firstName: 'Jane', lastName: 'Green', dob: '1985-07-22' },
        { id: 'P011', unitId: 'APPLE04', firstName: 'Kate', lastName: 'Walker', dob: '1999-11-01', flags: [{ id: 'flag-p11-1', message: 'Severe nut allergy. All staff must be aware.', level: 'danger' }] },
        { id: 'P012', unitId: 'BANAN01', firstName: 'Liam', lastName: 'Scott', dob: '1991-01-15' },
        { id: 'P013', unitId: 'BANAN02', firstName: 'Megan', lastName: 'Hill', dob: '1980-06-30' },
        { id: 'P014', unitId: 'BANAN03', firstName: 'Noah', lastName: 'Adams', dob: '2002-09-10' },
        { id: 'P015', unitId: 'CHERR01', firstName: 'Olivia', lastName: 'Baker', dob: '1978-02-28' },
        { id: 'P016', unitId: 'CHERR02', firstName: 'Peter', lastName: 'Clark', dob: '1996-08-14' },
        { id: 'P017', unitId: 'GRAPE01', firstName: 'Quinn', lastName: 'Evans', dob: '1993-05-18' },
        { id: 'P018', unitId: 'GRAPE02', firstName: 'Rachel', lastName: 'Morris', dob: '1987-12-03' },
        { id: 'P019', unitId: 'GRAPE03', firstName: 'Steven', lastName: 'Roberts', dob: '1995-10-25' },
        { id: 'P020', unitId: 'GRAPE04', firstName: 'Tina', lastName: 'Hughes', dob: '1998-04-05' },
        { id: 'P021', unitId: 'PEAR01', firstName: 'Uma', lastName: 'Phillips', dob: '1965-07-19', flags: [{ id: 'flag-p21-1', message: 'Attends day center Mon, Weds, Fri.', level: 'info' }] },
        { id: 'P022', unitId: 'STRAW01', firstName: 'Victor', lastName: 'James', dob: '2000-03-08' },
        { id: 'P023', unitId: 'STRAW02', firstName: 'Wendy', lastName: 'Davies', dob: '1982-11-11' },
        { id: 'P024', unitId: 'STRAW03', firstName: 'Xavier', lastName: 'Edwards', dob: '1990-09-02' },
        { id: 'P025', unitId: 'LIVP01', firstName: 'Yasmine', lastName: 'Carter', dob: '1997-06-06' },
        { id: 'P026', unitId: 'LIVP02', firstName: 'Zoe', lastName: 'Wright', dob: '1993-02-14' },
    ].map((p, index) => ({
        id: p.id, preferredFirstName: p.firstName, legalFirstName: p.firstName, surname: p.lastName,
        dob: p.dob, status: PersonStatus.Current,
        propertyId: MOCK_PROPERTIES.find(prop => prop.units.some(u => u.id === p.unitId))?.id || '',
        unitId: p.unitId, moveInDate: '2023-01-01', moveOutDate: null, keyWorkerId: 'NH01', areaManagerId: 'CB01',
        careNeeds: [], funding: [{ id: `fund-p${index+9}-1`, source: 'Local Authority', weeklyAmount: 800.00, details: '' }],
        tenancy: { type: 'Licence Agreement', startDate: '2023-01-01', documents: [] },
        timeline: [], documents: [], contacts: [], title: 'Mr', firstLanguage: 'English', isNonVerbal: false,
        ...p
    })) as Person[],
    ...MOCK_APPLICANTS,
];

export const MOCK_GROWTH_OPPORTUNITIES: GrowthOpportunity[] = [
    {
        id: 'GO-001',
        name: 'Nottingham City Residential Framework 2025 Renewal',
        opportunityType: OpportunityType.Framework,
        laId: 'la-ncc',
        bdLeadId: 'RL01',
        region: 'Midlands',
        serviceType: ServiceType.Residential,
        clientGroup: 'Complex Needs',
        beds: 50,
        status: BDStage.BidInProgress,
        dueDate: '2024-11-15',
        notes: 'Currently on Lot 2. Bid for Lot 1 in progress for renewal.'
    },
    {
        id: 'GO-002',
        name: 'North Yorkshire Supported Living Framework 2022-2026',
        opportunityType: OpportunityType.Framework,
        laId: 'la-nyc',
        bdLeadId: 'CC01',
        region: 'North',
        serviceType: ServiceType.SupportedLiving,
        clientGroup: 'Learning Disability',
        status: BDStage.Won,
        contractEndDate: '2026-06-30',
        notes: 'Tier 1 provider for complex needs. Strong relationship with commissioner Susan Collins.'
    },
    {
        id: 'GO-003',
        name: 'Cheshire West & Chester Mental Health Services',
        opportunityType: OpportunityType.Tender,
        laId: 'la-cwc',
        bdLeadId: 'RL01',
        region: 'North',
        serviceType: ServiceType.SupportedLiving,
        clientGroup: 'Mental Health',
        beds: 12,
        status: BDStage.Lost,
        decisionDate: '2024-06-20',
        notes: 'Lost on price. Feedback received and logged.'
    },
    {
        id: 'GO-004',
        name: 'Newport Nursing & Complex Care DPS',
        opportunityType: OpportunityType.Framework,
        laId: 'la-npt',
        bdLeadId: 'CC01',
        region: 'Wales',
        serviceType: ServiceType.NursingCare,
        clientGroup: 'Complex Physical Needs',
        status: BDStage.NotProgressed,
        notes: 'Framework expired. New tender expected Q4 2024. Currently operating on spot purchase agreements.'
    },
    {
        id: 'GO-005',
        name: 'Liverpool LD Services - Expression of Interest',
        opportunityType: OpportunityType.Tender,
        laId: 'la-liv',
        bdLeadId: 'RL01',
        region: 'North',
        serviceType: ServiceType.SupportedLiving,
        clientGroup: 'Learning Disability',
        beds: 25,
        status: BDStage.Potential,
        notes: 'Awaiting tender documents to be released.'
    },
     {
        id: 'GO-006',
        name: 'North Yorkshire Extra Care Bid',
        opportunityType: OpportunityType.Tender,
        laId: 'la-nyc',
        bdLeadId: 'CC01',
        region: 'North',
        serviceType: ServiceType.SupportedLiving,
        clientGroup: 'Older Adults',
        beds: 40,
        status: BDStage.Submitted,
        dueDate: '2024-08-30',
        decisionDate: '2024-10-15'
    },
    // --- New Build Schemes with Development Stages ---
    {
        id: 'GO-007',
        name: 'Harrogate New Build Scheme Feasibility',
        opportunityType: OpportunityType.NewBuild,
        laId: 'la-nyc',
        bdLeadId: 'MF01',
        region: 'North',
        serviceType: ServiceType.SupportedLiving,
        clientGroup: 'Autism',
        beds: 6,
        developmentStage: DevelopmentStage.Feasibility,
    },
    {
        id: 'GO-008',
        name: 'Nottingham Land Plot Sourcing',
        opportunityType: OpportunityType.NewBuild,
        laId: 'la-ncc',
        bdLeadId: 'RL01',
        region: 'Midlands',
        serviceType: ServiceType.Residential,
        clientGroup: 'Complex Needs',
        beds: 8,
        developmentStage: DevelopmentStage.Sourcing,
    },
    {
        id: 'GO-009',
        name: 'Chester CAPCOM Proposal',
        opportunityType: OpportunityType.NewBuild,
        laId: 'la-cwc',
        bdLeadId: 'CG01',
        region: 'North',
        serviceType: ServiceType.SupportedLiving,
        clientGroup: 'Mental Health',
        beds: 10,
        developmentStage: DevelopmentStage.Approval,
    },
    {
        id: 'GO-010',
        name: 'Derby Site Acquisition',
        opportunityType: OpportunityType.NewBuild,
        laId: 'la-derby',
        bdLeadId: 'MF01',
        region: 'Midlands',
        serviceType: ServiceType.SupportedLiving,
        clientGroup: 'Learning Disability',
        beds: 4,
        developmentStage: DevelopmentStage.Acquisition,
    },
    {
        id: 'GO-011',
        name: 'Sheffield Refurbishment Project',
        opportunityType: OpportunityType.NewBuild,
        laId: 'la-sheff',
        bdLeadId: 'AS01',
        region: 'North',
        serviceType: ServiceType.Residential,
        clientGroup: 'Challenging Behaviour',
        beds: 5,
        developmentStage: DevelopmentStage.Development,
    },
    {
        id: 'GO-012',
        name: 'Leeds Pre-Handover Checks',
        opportunityType: OpportunityType.NewBuild,
        laId: 'la-leeds',
        bdLeadId: 'AS01',
        region: 'North',
        serviceType: ServiceType.SupportedLiving,
        clientGroup: 'Autism',
        beds: 8,
        developmentStage: DevelopmentStage.PreHandover,
    },
    {
        id: 'GO-013',
        name: 'York House (Handed Over)',
        opportunityType: OpportunityType.NewBuild,
        laId: 'la-nyc',
        bdLeadId: 'CG01',
        region: 'North',
        serviceType: ServiceType.Residential,
        clientGroup: 'Complex Needs',
        beds: 6,
        developmentStage: DevelopmentStage.Complete,
    },
    {
        id: 'GO-014',
        name: 'Zucchini Street Development',
        opportunityType: OpportunityType.NewBuild,
        laId: 'la-manc',
        bdLeadId: 'CG01',
        region: 'North',
        serviceType: ServiceType.SupportedLiving,
        clientGroup: 'Learning Disability',
        beds: 8,
        developmentStage: DevelopmentStage.Development,
        notes: 'On-site build in progress. Target completion Q1 2025.'
    },
    {
        id: 'GO-015',
        name: 'Kumquat Avenue Acquisition',
        opportunityType: OpportunityType.NewBuild,
        laId: 'la-birm',
        bdLeadId: 'MF01',
        region: 'Midlands',
        serviceType: ServiceType.Residential,
        clientGroup: 'Mental Health',
        beds: 5,
        developmentStage: DevelopmentStage.Acquisition,
        notes: 'Legals underway with solicitors. Expected exchange date next month.'
    }
];


export const MOCK_COMMISSIONING_AUTHORITIES: string[] = [
    'Amber Valley Borough Council',
    'Arun District council',
    'Ashfield District Council',
    'Aylesbury Vale District Council',
    'Babergh District Council',
    'Barnet County Council',
    'Barnsley Metropolitan Borough Council',
    'Basingstoke & Deane Borough Council',
    'Bassetlaw District Council',
    'Bath & North East Somerset Council',
    'Bedford Borough Council',
    'Birmingham City Council',
    'Blackpool Council',
    'Aneurin Bevan University Health Board CGL',
    'Blackburn with darwen borough council',
    'Bolsover District Council',
    'Bolton Council',
    'Borough of Poole',
    'Boston Borough Council',
    'Bournemouth District Council',
    'Bradford MBC',
    'Braintree District Council',
    'Breckland Council',
    'Brighton & Hove City Council',
    'Bristol City Council',
    'Broadland District Council',
    'Bromsgrove District Council',
    'Broxtowe Borough Council',
    'Buckinghamshire Council',
    'Bury Council',
    'Calderdale MBC',
    'Cambridgeshire CC',
    'Cannock Chase Council',
    'Canterbury City Council',
    'Carlisle City Council',
    'Carmarthenshire County Council',
    'Central Bedfordshire',
    'Ceredigion County Council',
    'Charnwood Borough Council',
    'Chelmsford Borough Council',
    'Cheltenham Borough Council',
    'Cherwell District Council',
    'Cheshire East Council',
    'Cheshire West & Chester Council',
    'Chesterfield Borough Council',
    'Chichester District Council',
    'Chiltern District Council',
    'Christchurch Borough Council',
    'City and County of Cardiff',
    'City of Bradford Metropolitan District Council',
    'City of Lincoln Council',
    'City of York Council',
    'Colchester Borough Council',
    'Corby Borough Council',
    'Cornwall Council',
    'Coventry City Council',
    'Craven District Council',
    'Croydon Council',
    'Dacorum Borough Council',
    'Darlington Borough Council',
    'Dartford Borough Council',
    'Denbigshire County Council',
    'Derby City Council',
    'Derbyshire County Council',
    'Derbyshire Dales District Council',
    'Devon County Council',
    'Doncaster Metropolitan Borough Council',
    'Dover District Council',
    'Dudley Metropolitan Borough Council',
    'North East and North Cumbria ICB',
    'Durham County Council',
    'East Devon Council',
    'East Hampshire District Council',
    'East Herts Council',
    'East Lindsey District Council',
    'East Riding of Yorkshire Council',
    'East Staffordshire Borough Council',
    'East Suffolk Council',
    'Eastbourne Borough Council',
    'Eastleigh Borough Council',
    'Eden District Council',
    'Elmbridge Borough Council',
    'Enfield Council',
    'Erewash Borough Council',
    'Exeter City Council',
    'Essex County Council',
    'Fareham Borough Council',
    'Fenland District Council',
    'Flintshire County Council',
    'Folkestone & Hythe District Council',
    'Forest Heath District Council',
    'Forest of Dean District Council',
    'Fylde Borough Council',
    'Gateshead Council',
    'Gedling Borough Council',
    'Gloucester City Council',
    'Gravesham Borough Council',
    'Great Yarmouth Borough Council',
    'Guildford Borough Council',
    'Halton Borough Council',
    'Hambleton District Council',
    'Harborough District Council',
    'Haringey Council',
    'Harlow Council',
    'Harrogate Borough Council',
    'Hartlepool Borough Council',
    'Hastings Borough Council',
    'Havant Borough Council',
    'Herefordshire Council',
    'Hertsmere Borough Council',
    'High Peak Borough Council',
    'Hinckley and Bosworth Borough Council',
    'Hull City Council',
    'Huntingdonshire District Council',
    'Hyndburn Borough Council',
    'Ipswich Borough Council',
    'Isle of Anglesey County Council',
    'Kettering Borough Council',
    'Kingston upon Hull City Council',
    'Kirklees Council',
    'Knowsley Council',
    'Lancashire County Council',
    'Lancashire Foundation Trust',
    'Leeds City Council',
    'Leicester City Council',
    'Leicestershire County Council',
    'Lewes District Council',
    'Lichfield District Council',
    'Lincolnshire County Council',
    'Lincolnshire ICB',
    'Liverpool City Council',
    'London Borough Of Bexley',
    'London Borough of Brent',
    'London Borough of Bromley',
    'London Borough of Ealing',
    'London Borough of Greenwich',
    'London Borough of Hammersmith & Fulham',
    'London Borough of Havering',
    'London Borough of Hillingdon',
    'London Borough of Lambeth',
    'London Borough of Lewisham',
    'London Borough of Richmond Upon Thames',
    'London Borough of Southwark',
    'London Borough of Sutton',
    'Luton Borough Council',
    'Maidstone Borough Council',
    'Malvern Halls District Council',
    'Manchester City Council',
    'Mansfield District Council',
    'Melton Borough Council',
    'Mendip District Council',
    'Merton Council',
    'Mid Suffolk District Council',
    'Mid Sussex District Council',
    'Middlesbrough Council',
    'Milton Keynes Council',
    'Neath Port Talbot Borough Council',
    'New Forest District Council',
    'Newark & Sherwood District Council',
    'Newcastle-under-Lyme Borough Council',
    'Newham Council',
    'Newcastle upon tyne City Council',
    'Newport City Council',
    'NHS Humber and North Yorkshire ICB',
    'NHS Greater Manchester ICB',
    'NHS Lancashire & South Cumbria',
    'Norfolk County Council',
    'North East Derbyshire District Council',
    'North East Lincolnshire Council',
    'North Kesteven District Counci',
    'North Lincolnshire Council',
    'North Northamptonshire Council',
    'North Somerset Council',
    'North Tyneside Council',
    'North Warwickshire Borough Council',
    'North West Leicestershire District Council',
    'North Yorkshire CC',
    'Northampton Borough Council',
    'Northern Ireland',
    'Northumberland County Council',
    'Norwich City Council',
    'Nottingham City Council',
    'Nottinghamshire County Council',
    'Nuneaton and Bedworth Borough Council',
    'Oldham Council',
    'Oxford City Council',
    'Pembrokeshire County Council',
    'Peterborough City Council',
    'Plymouth City Council',
    'Portsmouth City Council',
    'Powys County Council',
    'Preston City Council',
    'Purbeck District Council',
    'Redbridge Council',
    'Redcar and Cleveland BC',
    'Redditch BC',
    'Reigate and Banstead Borough Council',
    'Ribble Valley Borough Council',
    'Richmondshire District Council',
    'Rochdale Metropolitan Borough Council',
    'Rother District Council',
    'Rotherham MBC',
    'Royal Kingston',
    'Rugby Borough Council',
    'Runnymede Borough Council',
    'Rushcliffe Borough Council',
    'Rushmoor Borough Council',
    'Rutland County Council',
    'Ryedale District Council',
    'Salford City Council',
    'Sandwell Council',
    'Scarborough Borough Council',
    'Sedgemoor District Council',
    'Sefton Council',
    'Selby District Council',
    'Sevenoaks District Council',
    'Sheffield City Council',
    'Shropshire and Telford & Wrekin Councils',
    'Slough Borough Council',
    'Solihull Metropolitan Borough Council',
    'Somerset County Council',
    'Somerset West and Taunton',
    'South Gloucestershire Council',
    'South Hams District Council',
    'South Holland District Council',
    'South Kesteven District Council',
    'South Oxfordshire District Council',
    'South Somerset DC',
    'South Tyneside Council',
    'Southampton City Council',
    'Southend Borough Council',
    'Spelthorne Borough Council',
    'St Albans City & District Council',
    'St Helens MBC',
    'Staffordshire Borough Council',
    'Stevenage Borough Council',
    'Stockport MBC',
    'Stockton on Tees Borough Council',
    'Stoke on Trent',
    'Stour Valley Partnership',
    'Stratford Upon Avon District',
    'Stroud District Council',
    'Suffolk County Council',
    'Sunderland City Council',
    'Sutton Council',
    'Swindon Borough Council',
    'Tameside MBC',
    'Tamworth Borough Council',
    'Tandridge District Council',
    'Taunton Deane Borough Council',
    'Teignbridge District Council',
    'Telford & Wrekin Council',
    'Tendring District Council',
    'Tees Valley Borough Council',
    'Tewkesbury Borough Council',
    'Thanet District Council',
    'Three Rivers District Council',
    'Tonbridge & Malling BC',
    'Torbay Council',
    'Torridge District Council',
    'Trafford Council',
    'Tunbridge Wells Borough Council',
    'Uttlesford District Council',
    'Wakefield Council',
    'Walsall Council',
    'Wandsworth Borough Council',
    'Warrington Borough Council',
    'Warwick District Council',
    'Warwickshire County Council',
    'Waveney District Council',
    'Waverley Borough Council',
    'Welwyn Hatfield Borough Council',
    'West Berkshire Council',
    'West Devon Borough Council',
    'West Dorset District Council',
    'West Lindsey District Council',
    'West Northamptonshire',
    'West Oxfordshire DC',
    'West Somerset Council',
    'West Sussex Council',
    'West Wiltshire District Council',
    'West Yorkshire ICB',
    'Weymouth and Portland Borough Council',
    'Wigan Metropolitan Borough Council',
    'Wiltshire Council',
    'Winchester City Council',
    'Wirral Council',
    'Woking Borough Council',
    'Wolverhampton City Council',
    'Worcester City Council',
    'Worthing Borough Council',
    'Wycombe District Council',
    'York City Council',
    'Yorkshire & Humber ICB',
    'Surrey CC',
    'OTHER'
];